public class MultiplicationTable {
    public static void main(String[] args) {
        System.out.println("Таблица умножения в двух вариантах");
        System.out.println(" 1*1=1  1*2=2   1*3=3   1*4=4   1*5=5   1*6=6   1*7=7   1*8=8   1*9=9   1*10=10");
        System.out.println(" 2*1=2  2*2=4   2*3=6   2*4=8   2*5=10  2*6=12  2*7=14  2*8=16  2*9=18  2*10=20");
        System.out.println(" 3*1=3  3*2=6   3*3=9   3*4=12  3*5=15  3*6=18  3*7=21  3*8=24  3*9=27  3*10=30");
        System.out.println(" 4*1=4  4*2=8   4*3=12  4*4=16  4*5=20  4*6=24  4*7=28  4*8=32  4*9=36  4*10=40");
        System.out.println(" 5*1=5  5*2=10  5*3=15  5*4=20  5*5=25  5*6=30  5*7=35  5*8=40  5*9=45  5*10=50");
        System.out.println(" 6*1=6  6*2=12  6*3=18  6*4=24  6*5=30  6*6=36  6*7=42  6*8=48  6*9=54  6*10=60");
        System.out.println(" 7*1=7  7*2=14  7*3=21  7*4=28  7*5=35  7*6=42  7*7=49  7*8=56  7*9=63  7*10=70");
        System.out.println(" 8*1=8  8*2=16  8*3=24  8*4=32  8*5=40  8*6=48  8*7=56  8*8=64  8*9=72  8*10=80");
        System.out.println(" 9*1=9  9*2=18  9*3=27  9*4=36  9*5=45  9*6=54  9*7=64  9*8=72  9*9=81  9*10=90");
        System.out.println("10*1=10 10*2=20 10*3=30 10*4=40 10*5=50 10*6=60 10*7=70 10*8=80 10*9=90 10*10=100");
        int q = 1;
        int w = 2;
        int e = 3;
        int r = 4;
        int t = 5;
        int y = 6;
        int u = 7;
        int i = 8;
        int o = 9;
        int p = 10;

        System.out.printf("%5d" , (q*q));
        System.out.printf("%5d" , (q*w));
        System.out.printf("%5d" , (q*e));
        System.out.printf("%5d" , (q*r));
        System.out.printf("%5d" , (q*t));
        System.out.printf("%5d" , (q*y));
        System.out.printf("%5d" , (q*u));
        System.out.printf("%5d" , (q*i));
        System.out.printf("%5d" , (q*o));
        System.out.printf("%5d" , (q*p));
        System.out.println();
        System.out.printf("%5d" , (w*q));
        System.out.printf("%5d" , (w*w));
        System.out.printf("%5d" , (w*e));
        System.out.printf("%5d" , (w*r));
        System.out.printf("%5d" , (w*t));
        System.out.printf("%5d" , (w*y));
        System.out.printf("%5d" , (w*u));
        System.out.printf("%5d" , (w*i));
        System.out.printf("%5d" , (w*o));
        System.out.printf("%5d" , (w*p));
        System.out.println();
        System.out.printf("%5d" , (e*q));
        System.out.printf("%5d" , (e*w));
        System.out.printf("%5d" , (e*e));
        System.out.printf("%5d" , (e*r));
        System.out.printf("%5d" , (e*t));
        System.out.printf("%5d" , (e*y));
        System.out.printf("%5d" , (e*u));
        System.out.printf("%5d" , (e*i));
        System.out.printf("%5d" , (e*o));
        System.out.printf("%5d" , (e*p));
        System.out.println();
        System.out.printf("%5d" , (r*q));
        System.out.printf("%5d" , (r*w));
        System.out.printf("%5d" , (r*e));
        System.out.printf("%5d" , (r*r));
        System.out.printf("%5d" , (r*t));
        System.out.printf("%5d" , (r*y));
        System.out.printf("%5d" , (r*u));
        System.out.printf("%5d" , (r*i));
        System.out.printf("%5d" , (r*o));
        System.out.printf("%5d" , (r*p));
        System.out.println();
        System.out.printf("%5d" , (t*q));
        System.out.printf("%5d" , (t*w));
        System.out.printf("%5d" , (t*e));
        System.out.printf("%5d" , (t*r));
        System.out.printf("%5d" , (t*t));
        System.out.printf("%5d" , (t*y));
        System.out.printf("%5d" , (t*u));
        System.out.printf("%5d" , (t*i));
        System.out.printf("%5d" , (t*o));
        System.out.printf("%5d" , (t*p));
        System.out.println();
        System.out.printf("%5d" , (y*q));
        System.out.printf("%5d" , (y*w));
        System.out.printf("%5d" , (y*e));
        System.out.printf("%5d" , (y*r));
        System.out.printf("%5d" , (y*t));
        System.out.printf("%5d" , (y*y));
        System.out.printf("%5d" , (y*u));
        System.out.printf("%5d" , (y*i));
        System.out.printf("%5d" , (y*o));
        System.out.printf("%5d" , (y*p));
        System.out.println();
        System.out.printf("%5d" , (u*q));
        System.out.printf("%5d" , (u*w));
        System.out.printf("%5d" , (u*e));
        System.out.printf("%5d" , (u*r));
        System.out.printf("%5d" , (u*t));
        System.out.printf("%5d" , (u*y));
        System.out.printf("%5d" , (u*u));
        System.out.printf("%5d" , (u*i));
        System.out.printf("%5d" , (u*o));
        System.out.printf("%5d" , (u*p));
        System.out.println();
        System.out.printf("%5d" , (i*q));
        System.out.printf("%5d" , (i*w));
        System.out.printf("%5d" , (i*e));
        System.out.printf("%5d" , (i*r));
        System.out.printf("%5d" , (i*t));
        System.out.printf("%5d" , (i*y));
        System.out.printf("%5d" , (i*u));
        System.out.printf("%5d" , (i*i));
        System.out.printf("%5d" , (i*o));
        System.out.printf("%5d" , (i*p));
        System.out.println();
        System.out.printf("%5d" , (o*q));
        System.out.printf("%5d" , (o*w));
        System.out.printf("%5d" , (o*e));
        System.out.printf("%5d" , (o*r));
        System.out.printf("%5d" , (o*t));
        System.out.printf("%5d" , (o*y));
        System.out.printf("%5d" , (o*u));
        System.out.printf("%5d" , (o*i));
        System.out.printf("%5d" , (o*o));
        System.out.printf("%5d" , (o*p));
        System.out.println();
        System.out.printf("%5d" , (p*q));
        System.out.printf("%5d" , (p*w));
        System.out.printf("%5d" , (p*e));
        System.out.printf("%5d" , (p*r));
        System.out.printf("%5d" , (p*t));
        System.out.printf("%5d" , (p*y));
        System.out.printf("%5d" , (p*u));
        System.out.printf("%5d" , (p*i));
        System.out.printf("%5d" , (p*o));
        System.out.printf("%5d" , (p*p));



    }
}
